source 'https://rubygems.org'

gemspec

gem 'birch'
gem 'schiphol', git: 'git@github.com:hgcode/schiphol.git', ref: '5c509af'
gem 'yomu', git: 'git@github.com:hgcode/yomu.git', ref: '9f98379'
gem 'ruby-readability'
gem 'nokogiri'

group :test do
  gem 'rspec'
  gem 'rake'
  gem 'terminal-table'
  gem 'simplecov'
end

gem 'json', '~> 2.6', '>= 2.6.3'
gem 'rubyzip', '~> 2.3.2'
gem 'progressbar', '~> 1.13.0'
gem 'linguistics'
gem 'engtagger'
gem 'open-nlp'
gem 'stanford-core-nlp'
gem 'rwordnet'
gem 'scalpel'
gem 'fastimage'
gem 'decisiontree'
gem 'whatlanguage'
gem 'zip'
gem 'nickel'
gem 'tactful_tokenizer'
gem 'srx-english'
gem 'punkt-segmenter'
gem 'chronic'
gem 'uea-stemmer'
gem 'rbtagger'
gem 'ruby-stemmer'
gem 'activesupport'
gem 'rb-libsvm'
gem 'tomz-liblinear-ruby-swig'
gem 'ruby-fann'
gem 'fuzzy-string-match'
gem 'levenshtein-ffi'
gem 'tf-idf-similarity'
gem 'kronic'

